---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgB1hfO/WOHQ4V8r8vjY617J9fj62FgjDybXuLx4z1rvZokpMCFDl7gVCstVMuFYlNBIU/1Yc/P5NKZqmAcpnLz4rJ7cbMR4TWCGQ/R/Oaalc+YCj4HQ2bFdcqDjqcJMkJDwvtNTgnJmJawUKqarOdwrQX4jvAZGkyGP8ebEBgU5ufR6GMzhUKs+ZPutmWw1WTn73BWKipvJW/5xUdrRMyqHVLfj/F8Xu07udt1FytxaM9R6tTM134yJLHSHuBromLvOWpqj5FTbOnEvaFnyMyZAYT4RU/BC93CjWjs3quHW+J3v6swIGxa+EClxn91pdUpomSQO1xb57GQUsxoYErXLh7lkpazSmQnw05rEM4jkqjNLUOMWeL7yddelKKmbTrFLeuMU6FY0zCuiptVAa/ntVargG//6XkiweCXofSzpuEuOKuCFGSQhfOU2VcVioWxCjFhN2QbfF15l+PfiG5ncXuFDHG9SZkviJn0MSlBINcJuW/LCmogsFbd5ZvyUX0o8t326o8+s1DJVAgnkn+vYJ+oEXeKtlrzNeXHfbKU3bu7tihDJvN3PgN26tQBosDNlED8IM+r0RzXGhqFGbJSuxPCl3/G00NuUQHixDulVkj8UXesWVcMWH8RuaR8zOKP8ozoAfmbQk6Aw5R+kiJfZZqv43oXthA68g8CnKUrwhJsC3j4ohnFouaFaGqevtQNbeQDJmK4A+mfxOg==
    STRIPE_API_KEY: AgAakdLzmndG6potDCwFlpY3RJszdPpUzQfkTb15+aygtkcp8hbkmgMDrBv8h1IaccmZH3PISVoc262IGbyyO/MhQaC8D+pERdmjn9IwJmlzQzDG4Mm83Zs1j3wf88vvJlvCrLh2jLKY7oZO8JK3hxk7YRRyFuUFJv2OMrAKoEbzAnPfWLHUl+eFXqggE1qXafy+Y9YJiN+qkQ2jE6xq9YMNklPOews/+X+5aik0x9hnnopcWUJRRoH2vzUcoERNki1GL0Vg7TZJ+IiGHjUsQkophyYnyl1Ega8LORg7ixQJmTqwn67QNF1LMDDgsG4ID118F+pxfh2BB4kJG+fonxKksR7nX5DXLhIKVCR1+gb8rrDVVsL4516d2Xy4DpwyLw54JxkiMDiQELwtOjuFS3V2xowCbEx12kQqTlXG+gyy7LHXvpuMbNV7WuiL5lROUDKJWbu2FTBAEMtZeBAjLSLyO9rLo0PxUNgJybR/4Re6jvwJrZJXoPSMbwfDfVhMMfxjBqU1Z6BAgv6NsVVczpt9HAz0Lp1Zbm1J7bgVRhLdek7zigceDfXeWmrRXP3lkGaxrYKesBiMF/sF3zQ+3YkbrcipNq3JhxCrbyunu+ZAjNxqdWdJtABMqaWcP9CMIeZt+1LprY7ff2Vy09gWr2NnUS8tnnkZ8Su4Rkw9bbCY0A5Ih25lq76ApnIRAdU/qO3ZgeRpCeZQl0TdBqgTgRcf8nGpZRm1byFLMrvhPw==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
